global using System;
global using ReactWithDotNet;
global using System.Collections.Generic;
global using System.Linq;
global using static ReactWithDotNet.Mixin;
global using static ApiInspector.WebUI.Extensions;
global using static DotNetDependencyExtractor.Extensions;
global using System.Threading.Tasks;
global using static DotNetDependencyExtractor.Extractor;
global using DotNetDomainBoundarySpecifier.DataStore;
global using System.Collections.Immutable;
global using DotNetDomainBoundarySpecifier.Utilities;